package com.project.biblioteca.enums;

public enum Status {
    SUCESSO,
    CLIENTE_NAO_ENCONTRADO,
    LIVRO_NAO_ENCONTRADO,
    MAX_LIVROS_EXCEDIDO,
    LIVRO_INDISPONIVEL,
    CLIENTE_NAO_POSSUI_EMPRESTIMOS,
    LIVRO_DEVOLVIDO_COM_ATRASO,
    EMPRESTIMO_NAO_ENCONTRADO,
    RENOVACAO_SUCESSO
}