services:

  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=1475369
      - POSTGRES_USER=postgres
      - POSTGRES_DB=biblioteca-db
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - my-network 

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    networks:
      - my-network 

networks:
  my-network:
    driver: bridge
